### ISSUE TITLE
glibc 2.17

### ISSUE THREAD

**Issue by sakshatshinde** [rust-lang/docker-rust#150]
I don't think there is an official docker-rust image which has glibc 2.17
I tried Debian buster even that didn't have - 2.17

Is there any official image witch that specific glibc?

**Comment by sfackler** [comment]
There is no official image with that glibc version. I believe you'd need to go back to CentOS 7 for that.

**Comment by sakshatshinde** [comment]
One can easily achieve this using the following GitHub workflow.

```yaml
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main-centos"
    
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source "$HOME/.cargo/env" && cargo build --quiet --release
    - name: Artifact
      uses: actions/upload-artifact@v3
      with: 
        path: ${{ github.workspace }}/target/release/<project>
```
